# Generated by Django 4.0.1 on 2022-02-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок статьи')),
                ('title_two', models.CharField(max_length=150, verbose_name='Подзаголовок статьи')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Размещено')),
                ('author', models.CharField(max_length=70, verbose_name='Автор')),
                ('comment', models.TextField(verbose_name='Комментарии')),
                ('first_part', models.TextField(verbose_name='Вводная часть')),
                ('full_part', models.TextField(verbose_name='Полная часть')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, unique=True, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фотографии галереи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WriteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Написать комментарий')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('name', models.CharField(max_length=70, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PCD', 'Обработано'), ('NPD', 'Не обработано')], max_length=3, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=70, verbose_name='Автор')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.article', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.photo', verbose_name='Фото'),
        ),
    ]
