# Generated by Django 4.0.1 on 2022-02-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['id'], 'verbose_name': 'Фотографии галереи', 'verbose_name_plural': 'Фотографии галереи'},
        ),
        migrations.AlterModelOptions(
            name='writecomment',
            options={'verbose_name': 'Написать комментарий', 'verbose_name_plural': 'Написать комментарии'},
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
